name: "Docker Windows ARM64 Installer"
description: "Installs Docker Desktop on Windows ARM64 runners with Windows containers"
inputs:
  username:
    description: "Docker registry username"
    required: false
  password:
    description: "Docker registry password"
    required: false
  registry:
    description: "Docker registry (default: ghcr.io)"
    required: false
    default: "ghcr.io"
  use_windows_containers:
    description: "Use Windows containers instead of Linux (recommended for ARM64)"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    # Step 1: Download Docker Desktop installer for ARM64
    - name: Download Docker Desktop ARM64
      shell: powershell
      run: |
        $installer = "Docker Desktop Installer.exe"
        Write-Host "Downloading Docker Desktop for ARM64..."
        Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/arm64/Docker%20Desktop%20Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-arm64" -OutFile $installer
        Write-Host "Download complete."
    
    # Step 2: Install Docker silently with Windows containers
    - name: Install Docker Desktop
      shell: powershell
      run: |
        Write-Host "Installing Docker Desktop..."
        if ("${{ inputs.use_windows_containers }}" -eq "true") {
          Start-Process -Wait -FilePath ".\Docker Desktop Installer.exe" -ArgumentList "install", "--quiet", "--accept-license", "--backend=windows"
          Write-Host "Installation complete (Windows containers mode)."
        } else {
          Start-Process -Wait -FilePath ".\Docker Desktop Installer.exe" -ArgumentList "install", "--quiet", "--accept-license"
          Write-Host "Installation complete (Linux containers mode)."
        }
    
    # Step 3: Add Docker to PATH
    - name: Add Docker to PATH
      shell: powershell
      run: |
        $possiblePaths = @(
          "C:\Program Files\Docker\Docker\resources\bin",
          "C:\Program Files\Docker\Docker\Resources\bin",
          "C:\ProgramData\DockerDesktop\version-bin"
        )
        
        $dockerBin = $null
        foreach ($path in $possiblePaths) {
          if (Test-Path $path) {
            $dockerBin = $path
            Write-Host "Found Docker binaries at: $dockerBin"
            break
          }
        }
        
        if (-not $dockerBin) {
          throw "Docker binaries not found in any expected location"
        }
        
        echo "$dockerBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "$dockerBin;$env:PATH"
        Write-Host "Docker added to PATH"
    
    # Step 4: Start Docker service directly (no Desktop UI needed in CI)
    - name: Start Docker Service
      shell: powershell
      run: |
        Write-Host "Starting Docker service..."
        try {
          Start-Service docker -ErrorAction Stop
          Write-Host "Docker service started successfully."
        } catch {
          Write-Host "Docker service not available, starting Docker Desktop..."
          Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
        }
    
    # Step 5: Wait for Docker daemon
    - name: Wait for Docker daemon
      shell: powershell
      run: |
        Write-Host "Waiting for Docker daemon..."
        $maxWait = 180
        $interval = 5
        $elapsed = 0
        
        while ($elapsed -lt $maxWait) {
          try {
            docker version 2>&1 | Out-Null
            if ($LASTEXITCODE -eq 0) {
              Write-Host "Docker daemon is ready!"
              break
            }
          } catch {
            # Continue waiting
          }
          
          if ($elapsed % 30 -eq 0 -and $elapsed -gt 0) {
            Write-Host "  Still waiting... ($elapsed/$maxWait seconds)"
          }
          
          Start-Sleep -Seconds $interval
          $elapsed += $interval
        }
        
        if ($elapsed -ge $maxWait) {
          throw "Docker daemon did not start within $maxWait seconds."
        }
    
    # Step 6: Verify Docker
    - name: Verify Docker Installation
      shell: powershell
      run: |
        Write-Host "`n=== Docker Version ==="
        docker version
        
        Write-Host "`n=== Docker Info ==="
        docker info
    
    # Step 7: Docker Login
    - name: Docker Login (Optional)
      if: ${{ inputs.username != '' && inputs.password != '' }}
      shell: powershell
      run: |
        Write-Host "Logging in to ${{ inputs.registry }}..."
        echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u "${{ inputs.username }}" --password-stdin
        Write-Host "Login successful."
